// src/views/Contact.vue
<template>
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
    <div class="text-center mb-16">
      <h1 class="text-4xl font-extrabold text-gray-900 mb-4">Contact Us</h1>
      <p class="text-xl text-gray-600">We'd love to hear from you. Send us a message and we'll respond as soon as possible.</p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-12">
      <div>
        <form class="space-y-6">
          <div>
            <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
            <input
              type="text"
              id="name"
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            >
          </div>
          <div>
            <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
            <input
              type="email"
              id="email"
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            >
          </div>
          <div>
            <label for="message" class="block text-sm font-medium text-gray-700">Message</label>
            <textarea
              id="message"
              rows="4"
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            ></textarea>
          </div>
          <button
            type="submit"
            class="w-full bg-gray-900 text-white px-4 py-2 rounded hover:bg-gray-800"
          >
            Send Message
          </button>
        </form>
      </div>

      <div class="space-y-8">
        <div>
          <h2 class="text-2xl font-bold text-gray-900 mb-4">Get in Touch</h2>
          <div class="space-y-4">
            <p class="flex items-center text-gray-600">
              <span class="font-medium mr-2">Address:</span>
              123 Fashion Street, Style City, ST 12345
            </p>
            <p class="flex items-center text-gray-600">
              <span class="font-medium mr-2">Email:</span>
              info@sutex.com
            </p>
            <p class="flex items-center text-gray-600">
              <span class="font-medium mr-2">Phone:</span>
              (123) 456-7890
            </p>
          </div>
        </div>

        <div>
          <h2 class="text-2xl font-bold text-gray-900 mb-4">Business Hours</h2>
          <div class="space-y-2 text-gray-600">
            <p>Monday - Friday: 9:00 AM - 6:00 PM</p>
            <p>Saturday: 10:00 AM - 4:00 PM</p>
            <p>Sunday: Closed</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// src/components/Contact.jsx
import React from 'react';
import { FaEnvelope, FaPhone, FaWhatsapp, FaSkype } from 'react-icons/fa';

function Contact() {
  return (
    <div className="max-w-7xl mx-auto px-4 py-12">
      <div className="max-w-3xl mx-auto">
        <h2 className="text-3xl font-bold text-center mb-12">Contact Us</h2>
        
        <div className="bg-white rounded-lg shadow-md p-8">
          <div className="space-y-6">
            <div className="flex items-center">
              <FaEnvelope className="text-blue-600 text-xl mr-4" />
              <div>
                <h3 className="text-lg font-semibold">Email</h3>
                <p className="text-gray-600">sales@plasticpro.com</p>
              </div>
            </div>

            <div className="flex items-center">
              <FaPhone className="text-blue-600 text-xl mr-4" />
              <div>
                <h3 className="text-lg font-semibold">Phone</h3>
                <p className="text-gray-600">+1 (555) 123-4567</p>
              </div>
            </div>

            <div className="flex items-center">
              <FaWhatsapp className="text-blue-600 text-xl mr-4" />
              <div>
                <h3 className="text-lg font-semibold">WhatsApp</h3>
                <p className="text-gray-600">+1 (555) 123-4567</p>
              </div>
            </div>

            <div className="flex items-center">
              <FaSkype className="text-blue-600 text-xl mr-4" />
              <div>
                <h3 className="text-lg font-semibold">Skype</h3>
                <p className="text-gray-600">plasticpro.sales</p>
              </div>
            </div>
          </div>

          <div className="mt-8 pt-8 border-t">
            <h3 className="text-lg font-semibold mb-4">Send us a message</h3>
            <form className="space-y-4">
              <div>
                <label className="block text-gray-700 mb-2">Name</label>
                <input
                  type="text"
                  className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div>
                <label className="block text-gray-700 mb-2">Email</label>
                <input
                  type="email"
                  className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div>
                <label className="block text-gray-700 mb-2">Message</label>
                <textarea
                  className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                  rows="4"
                ></textarea>
              </div>
              <button
                type="submit"
                className="w-full bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700"
              >
                Send Message
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Contact
